generatorName: csharp-netcore
httpUserAgent: Tatum_SDK_CSharp
library: httpclient
globalProperties:
  generateAliasAsModel: false
  modelTests: false
  apiTests: false
  apiDocs: false
  modelDocs: false
additionalProperties: 
  licenseId: MIT
  sourceFolder: ""
releaseNote: "Include Blockchain Fees operations in packages. Tatum.CSharp.BlockchainFees package released."