generatorName: csharp-netcore
httpUserAgent: Tatum_SDK_CSharp
library: httpclient
globalProperties:
  generateAliasAsModel: false
  modelTests: false
  apiTests: false
  apiDocs: false
  modelDocs: false
additionalProperties: 
  licenseId: MIT
  packageName: Tatum.CSharp.Core
  sourceFolder: ""
  chainsToInclude: ETH-BTC-MATIC-BSC-ONE
releaseNote: "Harmony chain introduced. NFT support for Harmony."