generatorName: csharp-netcore
httpUserAgent: Tatum_SDK_CSharp
library: httpclient
globalProperties:
  generateAliasAsModel: false
  modelTests: false
  apiTests: false
  apiDocs: false
  modelDocs: false
additionalProperties: 
  licenseId: MIT
  packageName: Tatum.CSharp.Core
  sourceFolder: ""
releaseNote: "NFT support for Ethereum. Minor improvements to embedded documentation. Removed unused dependencies."