generatorName: csharp-netcore
httpUserAgent: Tatum_CSharp_SDK
library: httpclient
globalProperties:
  generateAliasAsModel: false
  modelTests: false
  apiTests: false
  apiDocs: false
  modelDocs: false
additionalProperties: 
  licenseId: MIT
  packageName: Tatum.CSharp.Core
  sourceFolder: ""