generatorName: csharp-netcore
httpUserAgent: Tatum_SDK_CSharp
library: httpclient
globalProperties:
  generateAliasAsModel: false
  modelTests: false
  apiTests: false
  apiDocs: false
  modelDocs: false
additionalProperties: 
  licenseId: MIT
  sourceFolder: ""
releaseNote: "Remove GET api calls for NTF and FT functionalities in blockchain packages that aren't supported by particular chain."