# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tatum - generate CSharp.Core from OpenAPI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Build_Version:
    name: Get Version
    uses: ./.github/workflows/calculateBuildVersion.yml
    
  Generate_Core:
    name: Generate Core Package
    runs-on: ubuntu-latest
    needs: Build_Version

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -f pom.xml -DskipTests
    - name: Generate Clients
      run: java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ./tatum/openapi_trim_trans.json -g csharp-netcore --library=httpclient --global-property generateAliasAsModel=false,modelTests=false,apiTests=false,apiDocs=false,modelDocs=false --additional-properties=packageName=Tatum.CSharp.Core,oneOfMappingFilePath=./tatum/oneOfMapping.json,sourceFolder=""
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Add package source
      run: dotnet nuget add source --username tatumio --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tatumio/index.json"
    - name: Restore dependencies
      run: dotnet restore ./Tatum.CSharp.Core/Tatum.CSharp.Core.csproj
    - name: Build
      run: dotnet build ./Tatum.CSharp.Core/Tatum.CSharp.Core.csproj --no-restore --configuration Release
    - name: Pack
      run: dotnet pack ./Tatum.CSharp.Core/Tatum.CSharp.Core.csproj --no-build --no-restore --configuration Release /p:Version=${{ needs.Build_Version.outputs.version }} --output .
    - name: Push to Github Packages
      run: dotnet nuget push "./Tatum.CSharp.Core.${{ needs.Build_Version.outputs.version }}.nupkg" --skip-duplicate --api-key ${{ secrets.ACTIONS_PACKAGE_SOURCE_PAT }} --source "github"
    - name: Trigger Tatum.CSharp workflow
      run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.DISPATCH_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          'https://api.github.com/repos/tatumio/tatum-csharp/actions/workflows/dotnet.yml/dispatches' \
          -d '{"ref": "develop", "inputs": {"source": "New Client code generated"}}'
