# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tatum - generate CSharp.Core from OpenAPI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  PACKAGE_SOURCE: https://nuget.pkg.github.com/tatumio/index.json
  MAPPING_PATH: ./tatum/oneOfMapping.json
  CONFIG_PATH: ./tatum/config.yaml

jobs:
  Generate_Cores:
    name: Generate Cores
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -f pom.xml -DskipTests
    - name: Prepare version control
      run: |
        git config --unset-all http.https://github.com/.extraheader
        git clone https://user:${{ secrets.DISPATCH_TOKEN }}@github.com/tatumio/tatum-csharp.git
        cd tatum-csharp
        git checkout develop
    - name: Generate Ethereum Core
      uses: ./.github/actions/generate-client
      with:
        package: Ethereum
        chains: ETH
    - name: Generate Bitcoin Core
      uses: ./.github/actions/generate-client
      with:
        package: Bitcoin
        chains: BTC
    - name: Generate Nft Core
      uses: ./.github/actions/generate-client
      with:
        package: Nft
        chains: ETH-BTC-MATIC-BSC-ONE
    - name: Generate FungibleTokens Core
      uses: ./.github/actions/generate-client
      with:
        package: FungibleTokens
        chains: ETH-BTC-MATIC-BSC-ONE
    - name: Generate MultiTokens Core
      uses: ./.github/actions/generate-client
      with:
        package: MultiTokens
        chains: ETH-BTC-MATIC-BSC-ONE
    - name: Generate BlockchainFees Core
      uses: ./.github/actions/generate-client
      with:
        package: BlockchainFees
        chains: ETH-BTC-MATIC-BSC-ONE
    - name: Generate NodeRpc Core
      uses: ./.github/actions/generate-client
      with:
        package: NodeRpc
        chains: ETH-BTC-MATIC-BSC-ONE
    - name: Generate Polygon Core
      uses: ./.github/actions/generate-client
      with:
        package: Polygon
        chains: MATIC
    - name: Generate Bsc Core
      uses: ./.github/actions/generate-client
      with:
        package: Bsc
        chains: BSC
    - name: Generate Harmony Core
      uses: ./.github/actions/generate-client
      with:
        package: Harmony
        chains: ONE
    - name: Generate Solana Core
      uses: ./.github/actions/generate-client
      with:
        package: Solana
        chains: SOL
    - name: Push to SDK repo
      run: |
          cd tatum-csharp
          git add .
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected, committing"
        
            git config user.name "generator-workflow"
            git config user.email "csharp-generator@tatum.io"
        
            git commit -m 'New Core generated'
            git push
          fi
